# Generated by Django 5.2.4 on 2025-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='sponsors/')),
                ('website', models.URLField()),
                ('competitions', models.ManyToManyField(blank=True, to='competitions.competition')),
            ],
        ),
    ]
