# Generated by Django 5.2.4 on 2025-07-30 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shooter_class', models.CharField(choices=[('PCP', 'PCP'), ('SPRINGER', 'SPRINGER')], max_length=20)),
                ('rifle', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
                ('pellets', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
