# Generated by Django 5.2.4 on 2025-08-25 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='score',
            new_name='first_day_score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='second_day_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tird_day_score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
