# Generated by Django 5.2.4 on 2025-09-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_score_userprofile_first_day_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_day_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='second_day_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tird_day_score',
        ),
    ]
