# Generated by Django 5.2.4 on 2025-08-04 07:58
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
