# Generated by Django 5.2.4 on 2025-08-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_rename_date_competition_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
