# Generated by Django 5.2.4 on 2025-08-25 12:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('competitions', '0003_delete_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shooter', to='accounts.userprofile')),
            ],
        ),
    ]
