# Generated by Django 5.2.4 on 2025-08-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='shooter',
        ),
        migrations.AddField(
            model_name='registration',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.score'),
        ),
    ]
