# Generated by Django 5.2.4 on 2025-08-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_remove_score_shooter_registration_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='score',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
