# Generated by Django 5.2.4 on 2025-09-08 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_registration_first_day_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_day_score',
            field=models.PositiveIntegerField(blank=True, default=0, error_messages={'max_value': 'Score cannot be more than 50'}, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='second_day_score',
            field=models.PositiveIntegerField(blank=True, default=0, error_messages={'max_value': 'Score cannot be more than 50'}, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tird_day_score',
            field=models.PositiveIntegerField(blank=True, default=0, error_messages={'max_value': 'Score cannot be more than 50'}, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
