# Generated by Django 5.2.4 on 2025-10-28 13:11

import field_target.competitions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_registration_first_day_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, validators=[field_target.competitions.validators.validate_competition_name]),
        ),
    ]
